doctrine:
  dbal:
    connections:
      default:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
      postgres:
          driver: pdo_pgsql
          port: 5400
          dbname: space_db
          user: symfony
          password: symfony
          charset: UTF8

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
#        TODO change directory
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
