framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
              middleware:

            query.bus: ~
            event.bus: ~

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
             async:
                 dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                 retry_strategy:
                    delay: 1000
             failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
             'App\Application\Expedition\Application\Handler\FinishExpeditionCommandHandler': async
             'App\Application\Expedition\Application\Handler\PlanNewExpeditionCommandHandler': async
             'App\Application\Expedition\Application\Handler\StartExpeditionCommandHandler': async
             'App\Application\Scientist\Application\Handler\MarkMarsScientistAsMissingOrDeadCommandHandler': async
             'App\Application\Scientist\Application\Handler\RegisterScientistCommandHandler': async