language: php
php:
  - 8.0
services:
  - postgresql
install:
  - composer install
before_script:
  - psql -c "CREATE USER symfony WITH PASSWORD 'symfony'" -U postgres
  - psql -c "CREATE DATABASE space_db;" -U postgres
script:
  - bin/console doctrine:schema:update --force
  - bin/phpunit
  - vendor/bin/ecs check --config vendor/landingi/php-coding-standards/ecs.php
  - vendor/bin/phpstan analyze -c phpstan.neon
env:
  global:
    - APP_ENV=test
