language: php
php:
  - 8.0
install:
  - composer install
  - composer update
script:
  - bin/phpunit
  - vendor/bin/ecs check --config vendor/landingi/php-coding-standards/ecs.php
  - vendor/bin/phpstan analyze -c phpstan.neon
