language: php
php:
  - 8.0
services:
  - postgresql
install:
  - composer install
script:
  - cd docker
  - docker compose up
  - bin/console doctrine:schema:update --force
  - bin/phpunit
  - vendor/bin/ecs check --config vendor/landingi/php-coding-standards/ecs.php
  - vendor/bin/phpstan analyze -c phpstan.neon
